data_source dbt_bigquery_core:
  type: bigquery
  connection:
    account_info_json_path:  
    auth_scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
    project_id: dbt_bigquery_core
    dataset: dbt_bigquery_core
soda_cloud:
  host: cloud.soda.io
  api_key_id: 
  api_key_secret: 