name: 'dbt_bigquery_core'
version: '1.0.0'
config-version: 2

profile: 'dbt-bigquery-core-profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bigquery_core:
    materialized: table
    intermediate:
      +materialized: view
    mart:
      +materialized: table
      +tags: ['mart', 'reporting']