dbt-bigquery-core-profile:
  target: prod  # Default to prod for BigQuery
  outputs:
    dev:
      extensions:
        - httpfs
        - parquet
      path: ./dbt.duckdb
      schema: dev
      threads: 1
      type: duckdb
    prod:
      type: bigquery
      method: service-account
      project: dbt-bigquery-core
      dataset: ingest_newsapi_v1  # Ensure the dataset name is correct
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/ekoepplin/dbt-bigquery-core-86e81e5718d0.json
      priority: interactive