dbt-bigquery-core-profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /tmp/dbt.duckdb
      schema: dev
      threads: 1
      extensions: 
        - httpfs
        - parquet
        - aws
    prod:
      dataset: dev_ekoepplin
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/ekoepplin/bigquery-dbt-core-credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: dbt-bigquery-core
      threads: 1
      type: bigquery