dbt-bigquery-core-profile:
  target: prod  # Default to prod for BigQuery
  outputs:
    dev:
      extensions:
        - httpfs
        - parquet
      path: /tmp/dbt.duckdb
      schema: dev
      threads: 1
      type: duckdb
    prod:
      type: bigquery
      method: service-account
      project: dbt-bigquery-core
      schema: dev_{{env_var('DBT_USER',env_var('USER','unknown'))}}
      location: EU
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      priority: interactive