dbt-bigquery-core-profile:
  target: dev  # Default to dev for BigQuery
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-bigquery-core
      schema: dev_{{env_var('DBT_USER',env_var('USER','unknown'))}}
      location: EU
      threads: 1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_SERVICE_ACCOUNT_KEY_PATH') }}"
      priority: interactive