[runtime]
log_level = "WARNING"  
dlthub_telemetry = true

[normalize]
loader_file_format="parquet"

[destination]
name = "filesystem"

[sources.filesystem] 
bucket_url='gcs://my_bucket'
file_glob="*"